apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rook-ceph-app-proj
  namespace: argocd
spec:
  description: AppProject for rook-ceph setup
  sourceRepos:
  - 'https://github.com/kaanastasiia/kubernetes-infra-setup.git'
  - 'https://charts.rook.io/release'
  destinations:
  - namespace: rook-ceph
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
    name: rook-ceph
  - group: 'rbac.authorization.k8s.io'
    kind: 'ClusterRole'
  - group: 'rbac.authorization.k8s.io'
    kind: 'ClusterRoleBinding'
  - group: 'apiextensions.k8s.io'
    kind: 'CustomResourceDefinition'
  - group: 'storage.k8s.io'
    kind: 'StorageClass'