apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rook-ceph-app-proj
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.19.4
    helm:
      releaseName: rook-ceph
      valueFiles:
      - rook-ceph.values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
    - CreateNamespace=true