apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  project: rook-ceph-app-proj
  sources:
    - repoURL: 'https://charts.rook.io/release'
      chart: rook-ceph
      targetRevision: v1.19.4
      helm:
        releaseName: rook-ceph
        valueFiles:
          - $values-repo/rook-ceph-setup/rook-ceph-operator-setup/operator-values.yaml
    - repoURL: 'https://github.com/kaanastasiia/kubernetes-infra-setup.git'
      targetRevision: main
      ref: values-repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
